// Code generated by Kitex v0.7.2. DO NOT EDIT.

package projectsservice

import (
	server "github.com/cloudwego/kitex/server"
	projects "github.com/li1553770945/personal-projects-service/kitex_gen/projects"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler projects.ProjectsService, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
